services:
  - type: web
    name: seg-app
    env: python
    plan: free
    buildCommand: >
      python build.py &&
      cd frontend &&
      npm install &&
      npm run build &&
      cd ../backend &&
      pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: VITE_API_URL
        scope: all
        value: "/api"
      - key: PORT
        scope: all
        value: "10000"
