export const resourceConfigs = {
  cargos: {
    title: 'Cargos / Funções',
    subtitle: 'Cadastre os cargos da empresa. Eles aparecem como opção no dropdown de colaboradores e podem ter um modelo padrão de permissões.',
    resource: 'cargos',
    createScope: 'create.cargos',
    filters: [
      { name: 'nome', label: 'Cargo', type: 'text' },
      { name: 'ativo', label: 'Ativo', type: 'select', options: [{ value: 'true', label: 'Sim' }, { value: 'false', label: 'Não' }] },
    ],
    columns: [
      { key: 'nome', label: 'Cargo' },
      { key: 'descricao', label: 'Descrição' },
      { key: 'ordem', label: 'Ordem' },
      { key: 'ativo', label: 'Ativo', type: 'boolean' },
    ],
    fields: [
      { name: 'nome', label: 'Nome do cargo', type: 'text', required: true, placeholder: 'Ex.: Motorista, Ajudante, Líder Operacional' },
      { name: 'descricao', label: 'Descrição', type: 'textarea', placeholder: 'Responsabilidades e âmbito do cargo' },
      { name: 'ordem', label: 'Ordem de exibição', type: 'number', placeholder: '1, 2, 3...' },
      { name: 'ativo', label: 'Ativo', type: 'checkbox', defaultValue: true },
    ],
  },
  filiais: {
    title: 'Filiais',
    subtitle: 'Cadastro operacional de unidades e parceiras, com dados de contato e CNPJ.',
    resource: 'filiais',
    filters: [
      { name: 'cidade', label: 'Cidade', type: 'text' },
      { name: 'uf', label: 'UF', type: 'text' },
      { name: 'parceira', label: 'Parceira', type: 'text' },
      {
        name: 'ativo',
        label: 'Ativo',
        type: 'select',
        options: [
          { value: 'true', label: 'Sim' },
          { value: 'false', label: 'Não' },
        ],
      },
    ],
    columns: [
      { key: 'cidade', label: 'Cidade' },
      { key: 'uf', label: 'UF' },
      { key: 'parceira', label: 'Parceira' },
      { key: 'cnpj', label: 'CNPJ' },
      { key: 'telefone_filial', label: 'Telefone' },
      { key: 'ativo', label: 'Ativo', type: 'boolean' },
    ],
    fields: [
      { name: 'cidade', label: 'Cidade', type: 'text', required: true, placeholder: 'Ex.: UBERLÂNDIA', transform: 'uppercase' },
      { name: 'uf', label: 'UF', type: 'text', required: true, placeholder: 'MG', transform: 'uppercase' },
      { name: 'parceira', label: 'Parceira', type: 'text', required: true, placeholder: 'Ex.: INTEGRA BRASIL', transform: 'uppercase' },
      { name: 'cnpj', label: 'CNPJ', type: 'text', placeholder: '00.000.000/0001-00' },
      { name: 'telefone_filial', label: 'Telefone', type: 'text', placeholder: '(34) 99999-9999' },
      { name: 'email_filial', label: 'E-mail da filial', type: 'email', placeholder: 'filial@empresa.com.br' },
      { name: 'endereco', label: 'Endereço', type: 'textarea', placeholder: 'Rua, número, bairro' },
      { name: 'ativo', label: 'Ativa', type: 'checkbox', defaultValue: true },
    ],
  },
  colaboradores: {
    title: 'Colaboradores',
    subtitle: 'Gestão de usuários internos, vínculo com filial e permissões. O usuário Supabase é vinculado automaticamente.',
    resource: 'colaboradores',
    importer: {
      templateUrl: '/modelos/modelo_importacao_colaboradores.csv',
      columns: [
        'filial',
        'nome_completo',
        'email',
        'cpf',
        'telefone',
        'cargo',
        'turno',
        'escala_servico',
        'horario_padrao_inicio',
        'horario_padrao_fim',
        'data_admissao',
        'data_desligamento',
      ],
      cpfMask: '000.000.000.00',
    },
    filters: [
      { name: 'nome_completo', label: 'Nome', type: 'text' },
      { name: 'cargo', label: 'Cargo', type: 'text' },
      { name: 'cpf', label: 'CPF', type: 'text' },
      { name: 'filial_id', label: 'Filial', type: 'select', relation: 'filiais', optionLabel: 'cidade' },
      {
        name: 'ativo',
        label: 'Ativo',
        type: 'select',
        options: [
          { value: 'true', label: 'Sim' },
          { value: 'false', label: 'Não' },
        ],
      },
      { name: 'data_desligamento', label: 'Data desligamento', type: 'date' },
    ],
    columns: [
      { key: 'nome_completo', label: 'Nome' },
      { key: 'filial_id', label: 'Filial' },
      { key: 'cargo', label: 'Cargo' },
      { key: 'ativo', label: 'Ativo', type: 'boolean' },
    ],
    fields: [
      { name: 'nome_completo', label: 'Nome completo', type: 'text', required: true },
      { name: 'email', label: 'E-mail do Supabase Auth', type: 'email', required: true, createOnly: true, showInDetails: false },
      { name: 'filial_id', label: 'Filial', type: 'select', required: true, relation: 'filiais', optionLabel: 'cidade' },
      { name: 'cpf', label: 'CPF', type: 'text', required: true },
      { name: 'telefone', label: 'Telefone', type: 'text' },
      { name: 'cargo', label: 'Cargo', type: 'select-text', required: true, relation: 'cargos', optionLabel: 'nome', placeholder: 'Selecione ou digite o cargo...' },
      {
        name: 'turno',
        label: 'Turno',
        type: 'select',
        options: [
          { value: 'manha', label: 'Manhã' },
          { value: 'tarde', label: 'Tarde' },
          { value: 'noite', label: 'Noite' },
          { value: 'administrativo', label: 'Administrativo' },
        ],
      },
      {
        name: 'escala_servico',
        label: 'Escala de serviço',
        type: 'select',
        options: [
          { value: 'seg-sex', label: 'segunda-sexta' },
          { value: 'seg-sab', label: 'segunda-sábado' },
          { value: 'seg-dom', label: 'segunda-domingo' },
          { value: '12x36', label: '12x36' },
          { value: '12x48', label: '12x48' },
          { value: '6x1', label: '6x1' },
          { value: '4x2', label: '4x2' },
          { value: '5x2', label: '5x2' },
        ],
      },
      { name: 'horario_padrao_inicio', label: 'Horário padrão início', type: 'time' },
      { name: 'horario_padrao_fim', label: 'Horário padrão fim', type: 'time' },
      { name: 'carga_horaria_semanal', label: 'Carga horária semanal', type: 'number', defaultValue: 44, placeholder: '44' },
      { name: 'intervalo_almoco_minutos', label: 'Intervalo almoço (min)', type: 'number', defaultValue: 60, placeholder: '60' },
      { name: 'salario_base_mensal', label: 'Salário base mensal', type: 'number', defaultValue: 0, placeholder: '0,00' },
      { name: 'percentual_periculosidade', label: 'Periculosidade (%)', type: 'number', defaultValue: 0, placeholder: 'Ex.: 30' },
      { name: 'percentual_adicional_clt', label: 'Adicional CLT (%)', type: 'number', defaultValue: 0, placeholder: 'Ex.: 20' },
      { name: 'adicional_noturno_sobre_periculosidade', label: 'Noturno incide sobre periculosidade', type: 'checkbox', defaultValue: false },
      { name: 'data_admissao', label: 'Data de admissão', type: 'date', required: true },
      { name: 'data_desligamento', label: 'Data de desligamento', type: 'date', helperText: 'Preencha apenas se o colaborador foi desligado. O status Ativo é definido automaticamente.' },
    ],
  },
  contratos_operacionais: {
    title: 'Contratos operacionais',
    subtitle: 'Gestão financeira por base. O cadastro do contrato guarda os dados macro; equipe, alocação e horas extras ficam na aba Equipe e valores e são somadas no contrato.',
    resource: 'contratos_operacionais',
    filters: [
      { name: 'codigo_contrato', label: 'Código', type: 'text' },
      { name: 'nome_contrato', label: 'Contrato', type: 'text' },
      { name: 'cliente_nome', label: 'Cliente', type: 'text' },
      { name: 'filial_id', label: 'Filial', type: 'select', relation: 'filiais', optionLabel: 'cidade' },
      {
        name: 'tipo_contrato',
        label: 'Tipo de contrato',
        type: 'select',
        options: [
          { value: 'rtm', label: 'RTM (Carregamento)' },
          { value: 'veiculos', label: 'Veículos' },
          { value: 'misto', label: 'Misto (RTM + Veículos)' },
        ],
      },
      {
        name: 'ativo',
        label: 'Ativo',
        type: 'select',
        options: [
          { value: 'true', label: 'Sim' },
          { value: 'false', label: 'Não' },
        ],
      },
    ],
    columns: [
      { key: 'codigo_contrato', label: 'Código' },
      { key: 'nome_contrato', label: 'Contrato' },
      { key: 'tipo_contrato', label: 'Tipo' },
      { key: 'cliente_nome', label: 'Cliente' },
      { key: 'filial_id', label: 'Filial', relation: 'filiais', optionLabel: 'cidade' },
      { key: 'qtd_colaboradores_contratados', label: 'Efetivo' },
      { key: 'valor_mensal_contrato', label: 'Valor ref. cadastro', type: 'currency' },
      { key: 'inicio_vigencia', label: 'Início vigência' },
      { key: 'ativo', label: 'Ativo', type: 'boolean' },
    ],
    fields: [
      { name: 'filial_id', label: 'Filial', type: 'select', required: true, relation: 'filiais', optionLabel: 'cidade' },
      { name: 'codigo_contrato', label: 'Código do contrato', type: 'text', required: true, placeholder: 'Ex.: CT-UDI-2026-001' },
      { name: 'nome_contrato', label: 'Nome do contrato', type: 'text', required: true, placeholder: 'Ex.: Contrato operação base Uberlândia' },
      {
        name: 'tipo_contrato',
        label: 'Tipo de contrato',
        type: 'select',
        required: true,
        defaultValue: 'rtm',
        tooltip: 'RTM = contrato de carregamento de cilindros. Veículos = locação/serviço de frota. Misto = RTM + frota juntos.',
        options: [
          { value: 'rtm', label: 'RTM (Carregamento)' },
          { value: 'veiculos', label: 'Veículos' },
          { value: 'misto', label: 'Misto (RTM + Veículos)' },
        ],
      },
      { name: 'cliente_nome', label: 'Cliente', type: 'select-text', relation: 'clientes', optionLabel: 'nome', placeholder: 'Nome do cliente contratante' },
      { name: 'valor_mensal_contrato', label: 'Valor mensal do contrato', type: 'number', required: false, defaultValue: 0, placeholder: '0,00' },
      { name: 'qtd_colaboradores_contratados', label: 'Qtd. colaboradores contratados', type: 'number', defaultValue: 0, placeholder: '0' },
      { name: 'cargos_contrato', label: 'Cargos previstos no contrato', type: 'textarea', placeholder: 'Ex.: 2 motoristas, 4 ajudantes, 1 líder' },
      
      { name: 'inicio_vigencia', label: 'Início da vigência', type: 'date' },
      { name: 'fim_vigencia', label: 'Fim da vigência', type: 'date' },
      { name: 'observacoes', label: 'Observações', type: 'textarea', placeholder: 'Condições comerciais, reajustes e observações' },
      { name: 'ativo', label: 'Ativo', type: 'checkbox', defaultValue: true },
    ],
  },
  contratos_colaboradores: {
    title: 'Equipe e valores do contrato',
    subtitle: 'Vincule colaboradores, caminhões ou itens ao contrato. Para cada linha: quem está, qual o % de alocação e quanto o cliente paga por esse item. Horas extras incluídas no contrato também ficam aqui.',
    resource: 'contratos_colaboradores',
    createScope: 'create.contratos_operacionais',
    filters: [
      { name: 'filial_id', label: 'Filial', type: 'select', relation: 'filiais', optionLabel: 'cidade' },
      {
        name: 'contrato_operacional_id',
        label: 'Contrato',
        type: 'select',
        relation: 'contratos_operacionais',
        optionLabel: 'nome_contrato',
        searchable: true,
        dependsOn: 'filial_id',
        dependsOnRelationField: 'filial_id',
      },
      {
        name: 'tipo_item',
        label: 'Tipo',
        type: 'select',
        options: [
          { value: 'colaborador', label: 'Colaborador (headcount oficial)' },
          { value: 'colaborador_fora_contrato', label: 'Colaborador fora do headcount' },
          { value: 'caminhao', label: 'Caminhão terceiro' },
          { value: 'veiculo_proprio', label: 'Veículo próprio (frota Gold)' },
          { value: 'pacote_motorista_veiculo', label: 'Pacote motorista + veículo' },
          { value: 'outro', label: 'Outro item' },
        ],
      },
      {
        name: 'colaborador_id',
        label: 'Colaborador',
        type: 'select',
        relation: 'colaboradores',
        optionLabel: 'nome_completo',
        searchable: true,
        dependsOn: 'filial_id',
        dependsOnRelationField: 'filial_id',
      },
      { name: 'ativo', label: 'Ativo', type: 'select', options: [{ value: 'true', label: 'Sim' }, { value: 'false', label: 'Não' }] },
    ],
    columns: [
      { key: 'tipo_item', label: 'Tipo' },
      { key: 'colaborador_id', label: 'Colaborador', relation: 'colaboradores', optionLabel: 'nome_completo' },
      { key: 'veiculo_proprio_id', label: 'Veículo próprio', relation: 'veiculos', optionLabel: 'placa' },
      { key: 'veiculo_carregamento_id', label: 'Caminhão terceiro', relation: 'veiculos_carregamento', optionLabel: 'placa' },
      { key: 'nome_item', label: 'Descrição' },
      { key: 'percentual_alocacao', label: 'Alocação %' },
      { key: 'valor_cobrado_colaborador', label: 'Valor cobrado ao cliente (R$)', type: 'currency' },
      { key: 'horas_50_cobradas', label: 'HE 50% incl.' },
      { key: 'horas_100_cobradas', label: 'HE 100% incl.' },
      { key: 'ativo', label: 'Ativo', type: 'boolean' },
    ],
    fields: [
      {
        name: 'filial_id',
        label: 'Filial',
        type: 'select',
        required: true,
        relation: 'filiais',
        optionLabel: 'cidade',
        tooltip: 'Base operacional deste contrato',
      },
      {
        name: 'contrato_operacional_id',
        label: 'Contrato',
        type: 'select',
        required: true,
        relation: 'contratos_operacionais',
        optionLabel: 'nome_contrato',
        searchable: true,
        dependsOn: 'filial_id',
        dependsOnRelationField: 'filial_id',
        requireDependsOn: true,
        tooltip: 'Selecione a filial primeiro para filtrar os contratos desta base',
      },
      {
        name: 'tipo_item',
        label: 'Tipo do item',
        type: 'select',
        required: true,
        defaultValue: 'colaborador',
        tooltip: 'Pacote motorista+veículo = uma linha agrupando motorista (colaborador) e veículo próprio com um único valor mensal.',
        options: [
          { value: 'colaborador', label: 'Colaborador' },
          { value: 'colaborador_fora_contrato', label: 'Colaborador extra (fora do contrato)' },
          { value: 'caminhao', label: 'Caminhão terceiro' },
          { value: 'veiculo_proprio', label: 'Veículo próprio (frota Gold)' },
          { value: 'pacote_motorista_veiculo', label: 'Pacote motorista + veículo próprio' },
          { value: 'outro', label: 'Outro item' },
        ],
      },
      {
        name: 'colaborador_id',
        label: 'Colaborador (motorista quando pacote)',
        type: 'select',
        requiredWhen: { field: 'tipo_item', in: ['colaborador', 'colaborador_fora_contrato', 'pacote_motorista_veiculo'] },
        visibleWhen: { field: 'tipo_item', in: ['colaborador', 'colaborador_fora_contrato', 'pacote_motorista_veiculo'] },
        relation: 'colaboradores',
        optionLabel: 'nome_completo',
        searchable: true,
        dependsOn: 'filial_id',
        dependsOnRelationField: 'filial_id',
      },
      {
        name: 'veiculo_carregamento_id',
        label: 'Caminhão terceiro',
        type: 'select',
        requiredWhen: { field: 'tipo_item', equals: 'caminhao' },
        visibleWhen: { field: 'tipo_item', equals: 'caminhao' },
        relation: 'veiculos_carregamento',
        optionLabel: 'placa',
        searchable: true,
        dependsOn: 'filial_id',
        dependsOnRelationField: 'filial_id',
      },
      {
        name: 'veiculo_proprio_id',
        label: 'Veículo próprio (frota Gold)',
        type: 'select',
        requiredWhen: { field: 'tipo_item', in: ['veiculo_proprio', 'pacote_motorista_veiculo'] },
        visibleWhen: { field: 'tipo_item', in: ['veiculo_proprio', 'pacote_motorista_veiculo'] },
        relation: 'veiculos',
        optionLabel: 'placa',
        searchable: true,
        dependsOn: 'filial_id',
        dependsOnRelationField: 'filial_id',
        tooltip: 'Veículo da nossa frota alocado ao contrato (filtrado pela filial)',
      },
      {
        name: 'nome_item',
        label: 'Descrição do item',
        type: 'text',
        placeholder: 'Ex.: equipamento, custo fixo, retroescavadeira',
        visibleWhen: { field: 'tipo_item', equals: 'outro' },
        requiredWhen: { field: 'tipo_item', equals: 'outro' },
      },
      {
        name: 'percentual_alocacao',
        label: 'Alocação no contrato (%)',
        type: 'number',
        defaultValue: 100,
        placeholder: '100',
      },
      {
        name: 'valor_cobrado_colaborador',
        label: 'Valor cobrado ao cliente (R$)',
        type: 'number',
        defaultValue: 0,
        placeholder: '0,00',
        tooltip: 'Pacote motorista+veículo: informe aqui o valor total da dupla. Veículo próprio sozinho: valor da locação. Colaborador: valor cobrado por esse colaborador.',
      },
      {
        name: 'horas_50_cobradas',
        label: 'HE 50% inclusas no contrato',
        type: 'number',
        defaultValue: 0,
        placeholder: '0',
      },
      {
        name: 'horas_100_cobradas',
        label: 'HE 100% inclusas no contrato',
        type: 'number',
        defaultValue: 0,
        placeholder: '0',
      },
      { name: 'inicio_vigencia', label: 'Início da vigência', type: 'date' },
      { name: 'fim_vigencia', label: 'Fim da vigência', type: 'date' },
      {
        name: 'data_inicio_vinculo',
        label: 'Início do vínculo operacional',
        type: 'date',
        visibleWhen: { field: 'tipo_item', in: ['colaborador', 'colaborador_fora_contrato'] },
        autoFill: {
          triggerField: 'colaborador_id',
          relation: 'colaboradores',
          sourceField: 'data_admissao',
        },
      },
      { name: 'dias_alerta_antes', label: 'Dias de alerta antes do vencimento', type: 'number', placeholder: '15' },
      { name: 'observacoes', label: 'Observações', type: 'textarea', placeholder: 'Ex.: cobertura de férias, alocação temporária' },
      { name: 'ativo', label: 'Ativo', type: 'checkbox', defaultValue: true },
    ],
  },
  contratos_gastos_extras: {
    title: 'Gastos extras do contrato',
    subtitle: 'Registre despesas operacionais adicionais que compõem o custo real do contrato (combustível, pedágio, diária, equipamento etc.). Informe o valor direto ou, quando vinculado a um colaborador, deixe o valor em 0 para calcular automaticamente pelo custo proporcional do colaborador.',
    resource: 'contratos_gastos_extras',
    createScope: 'create.contratos_operacionais',
    filters: [
      { name: 'filial_id', label: 'Filial', type: 'select', relation: 'filiais', optionLabel: 'cidade' },
      {
        name: 'contrato_operacional_id',
        label: 'Contrato',
        type: 'select',
        relation: 'contratos_operacionais',
        optionLabel: 'nome_contrato',
        searchable: true,
        dependsOn: 'filial_id',
        dependsOnRelationField: 'filial_id',
      },
      {
        name: 'colaborador_id',
        label: 'Colaborador',
        type: 'select',
        relation: 'colaboradores',
        optionLabel: 'nome_completo',
        searchable: true,
        dependsOn: 'filial_id',
        dependsOnRelationField: 'filial_id',
      },
      { name: 'nome_gasto', label: 'Gasto', type: 'text' },
      {
        name: 'ativo',
        label: 'Ativo',
        type: 'select',
        options: [
          { value: 'true', label: 'Sim' },
          { value: 'false', label: 'Não' },
        ],
      },
    ],
    columns: [
      { key: 'colaborador_id', label: 'Colaborador', relation: 'colaboradores', optionLabel: 'nome_completo' },
      { key: 'nome_gasto', label: 'Gasto' },
      { key: 'percentual_alocacao', label: 'Alocação %' },
      { key: 'valor_mensal', label: 'Valor (calc.)', type: 'currency' },
      { key: 'inicio_vigencia', label: 'Início' },
      { key: 'fim_vigencia', label: 'Fim' },
      { key: 'ativo', label: 'Ativo', type: 'boolean' },
    ],
    fields: [
      { name: 'filial_id', label: 'Filial', type: 'select', required: true, relation: 'filiais', optionLabel: 'cidade' },
      {
        name: 'contrato_operacional_id',
        label: 'Contrato',
        type: 'select',
        required: true,
        relation: 'contratos_operacionais',
        optionLabel: 'nome_contrato',
        searchable: true,
        dependsOn: 'filial_id',
        dependsOnRelationField: 'filial_id',
        requireDependsOn: true,
      },
      {
        name: 'colaborador_id',
        label: 'Colaborador',
        type: 'select',
        relation: 'colaboradores',
        optionLabel: 'nome_completo',
        searchable: true,
        dependsOn: 'filial_id',
        dependsOnRelationField: 'filial_id',
      },
      { name: 'percentual_alocacao', label: 'Alocação no contrato (%)', type: 'number', defaultValue: 100, placeholder: 'Ex.: 100 = custo total, 50 = metade', visibleWhen: { field: 'colaborador_id', notEmpty: true } },
      { name: 'nome_gasto', label: 'Descrição do gasto', type: 'text', required: true, placeholder: 'Ex.: custo por fora João, combustível, diária, pedágio' },
      { name: 'valor_mensal', label: 'Valor do gasto (R$)', type: 'number', placeholder: '0,00', hint: 'Quando vinculado a colaborador, informe 0 para calcular automaticamente pelo custo do colaborador.' },
      { name: 'inicio_vigencia', label: 'Início da vigência', type: 'date' },
      { name: 'fim_vigencia', label: 'Fim da vigência', type: 'date' },
      { name: 'observacoes', label: 'Observações', type: 'textarea', placeholder: 'Contexto do gasto e regra de cobrança' },
      { name: 'ativo', label: 'Ativo', type: 'checkbox', defaultValue: true },
    ],
  },
  colaborador_beneficios: {
    title: 'Benefícios por colaborador',
    subtitle: 'Configure benefícios fixos ou variáveis por colaborador, sem misturar valor mensal com valor por dia.',
    resource: 'colaborador_beneficios',
    createScope: 'create.colaboradores',
    filters: [
      { name: 'filial_id', label: 'Filial', type: 'select', relation: 'filiais', optionLabel: 'cidade' },
      {
        name: 'colaborador_id',
        label: 'Colaborador',
        type: 'select',
        relation: 'colaboradores',
        optionLabel: 'nome_completo',
        searchable: true,
        dependsOn: 'filial_id',
        dependsOnRelationField: 'filial_id',
      },
      { name: 'tipo_beneficio', label: 'Tipo', type: 'text' },
      {
        name: 'modo_calculo',
        label: 'Regra do benefício',
        type: 'select',
        options: [
          { value: 'fixo_mensal', label: 'Fixo mensal' },
          { value: 'por_dia', label: 'Variável por dia' },
          { value: 'percentual_salario', label: '% sobre salário' },
        ],
      },
      {
        name: 'ativo',
        label: 'Ativo',
        type: 'select',
        options: [
          { value: 'true', label: 'Sim' },
          { value: 'false', label: 'Não' },
        ],
      },
    ],
    columns: [
      { key: 'filial_id', label: 'Filial', relation: 'filiais', optionLabel: 'cidade' },
      { key: 'colaborador_id', label: 'Colaborador', relation: 'colaboradores', optionLabel: 'nome_completo' },
      { key: 'tipo_beneficio', label: 'Benefício' },
      { key: 'codigo_rubrica', label: 'Rubrica' },
      { key: 'valor_unitario', label: 'Valor por dia / %' },
      { key: 'mes_referencia_calculo', label: 'Mês referência', type: 'month' },
      { key: 'valor_total_projetado', label: 'Total projetado', type: 'currency' },
      { key: 'ativo', label: 'Ativo', type: 'boolean' },
    ],
    fields: [
      { name: 'filial_id', label: 'Filial', type: 'select', required: true, relation: 'filiais', optionLabel: 'cidade' },
      {
        name: 'colaborador_id',
        label: 'Colaborador',
        type: 'select',
        required: true,
        relation: 'colaboradores',
        optionLabel: 'nome_completo',
        searchable: true,
        dependsOn: 'filial_id',
        dependsOnRelationField: 'filial_id',
        requireDependsOn: true,
      },
      {
        name: 'tipo_beneficio',
        label: 'Tipo de benefício',
        type: 'select',
        required: true,
        defaultValue: 'vale_transporte',
        options: [
          { value: 'vale_transporte', label: 'Vale transporte' },
          { value: 'vale_refeicao', label: 'Vale refeição' },
          { value: 'vale_alimentacao', label: 'Vale alimentação' },
          { value: 'plano_saude', label: 'Plano de saúde' },
          { value: 'ajuda_custo', label: 'Ajuda de custo' },
          { value: 'bonificacao', label: 'Bonificação' },
          { value: 'premio', label: 'Prêmio' },
          { value: 'outro', label: 'Outro' },
        ],
      },
      {
        name: 'codigo_rubrica',
        label: 'Código da rubrica',
        type: 'select',
        defaultValue: 'VT',
        options: [
          { value: 'VT', label: 'VT' },
          { value: 'VR', label: 'VR' },
          { value: 'VA', label: 'VA' },
          { value: 'PS', label: 'Plano saúde' },
          { value: 'AJUDA', label: 'Ajuda de custo' },
          { value: 'BONUS', label: 'Bonificação' },
          { value: 'PREMIO', label: 'Prêmio' },
          { value: 'OUTRO', label: 'Outro' },
        ],
      },
      {
        name: 'modo_calculo',
        label: 'Regra do benefício',
        type: 'select',
        required: true,
        defaultValue: 'fixo_mensal',
        options: [
          { value: 'fixo_mensal', label: 'Fixo mensal' },
          { value: 'por_dia', label: 'Variável por dia elegível' },
          { value: 'percentual_salario', label: 'Percentual do salário' },
        ],
      },
      {
        name: 'base_dias',
        label: 'Apurar dias por',
        type: 'select',
        defaultValue: 'escala',
        options: [
          { value: 'presenca', label: 'Dias presentes' },
          { value: 'uteis', label: 'Dias úteis do mês' },
          { value: 'escala', label: 'Registros de presença/escala' },
          { value: 'calendario', label: 'Dias de calendário' },
        ],
      },
      { name: 'valor_mensal', label: 'Valor fixo mensal (use para benefício fixo)', type: 'number', required: true, defaultValue: 0, placeholder: '0,00' },
      { name: 'valor_unitario', label: 'Valor por dia ou percentual (use para variável ou %)', type: 'number', defaultValue: 0, placeholder: '0,00' },
      { name: 'desconta_faltas', label: 'Desconta faltas', type: 'checkbox', defaultValue: true },
      { name: 'desconta_eventos', label: 'Desconta férias/afastamentos', type: 'checkbox', defaultValue: true },
      { name: 'observacoes', label: 'Observações', type: 'textarea', placeholder: 'Regras, coparticipação, elegibilidade' },
      { name: 'ativo', label: 'Ativo', type: 'checkbox', defaultValue: true },
    ],
  },
  colaborador_documentos: {
    title: 'Documentos RH',
    subtitle: 'Controle documental do colaborador, com validade, anexo e renovação planejada.',
    resource: 'colaborador_documentos',
    filters: [
      { name: 'tipo_documento', label: 'Tipo', type: 'text' },
      { name: 'categoria', label: 'Categoria', type: 'text' },
      { name: 'status', label: 'Status', type: 'text' },
      { name: 'filial_id', label: 'Filial', type: 'select', relation: 'filiais', optionLabel: 'cidade' },
      { name: 'colaborador_id', label: 'Colaborador', type: 'select', relation: 'colaboradores', optionLabel: 'nome_completo' },
      {
        name: 'ativo',
        label: 'Ativo',
        type: 'select',
        options: [
          { value: 'true', label: 'Sim' },
          { value: 'false', label: 'Não' },
        ],
      },
    ],
    columns: [
      { key: 'colaborador_id', label: 'Colaborador', relation: 'colaboradores', optionLabel: 'nome_completo' },
      { key: 'filial_id', label: 'Filial', relation: 'filiais', optionLabel: 'cidade' },
      { key: 'categoria', label: 'Categoria' },
      { key: 'tipo_documento', label: 'Documento' },
      { key: 'data_validade', label: 'Validade' },
      { key: 'status_calculado', label: 'Status atual' },
      { key: 'dias_para_vencer', label: 'Dias p/ vencer' },
      { key: 'ativo', label: 'Ativo', type: 'boolean' },
    ],
    fields: [
      { name: 'colaborador_id', label: 'Colaborador', type: 'select', required: true, relation: 'colaboradores', optionLabel: 'nome_completo' },
      { name: 'filial_id', label: 'Filial', type: 'select', required: true, relation: 'filiais', optionLabel: 'cidade' },
      {
        name: 'categoria',
        label: 'Categoria',
        type: 'select',
        required: true,
        options: [
          { value: 'pessoal', label: 'Pessoal' },
          { value: 'saude', label: 'Saúde' },
          { value: 'habilitacao', label: 'Habilitação' },
          { value: 'treinamento', label: 'Treinamento' },
          { value: 'contratual', label: 'Contratual' },
        ],
      },
      { name: 'tipo_documento', label: 'Tipo do documento', type: 'text', required: true, placeholder: 'Ex.: CNH, ASO, NR-20, Contrato' },
      { name: 'numero_documento', label: 'Número', type: 'text', placeholder: 'Número ou identificação interna' },
      { name: 'orgao_emissor', label: 'Órgão emissor', type: 'text', placeholder: 'Ex.: Detran, clínica, SESI' },
      { name: 'data_emissao', label: 'Data de emissão', type: 'date' },
      { name: 'data_validade', label: 'Data de validade', type: 'date' },
      { name: 'dias_alerta', label: 'Alertar antes (dias)', type: 'number', defaultValue: 30, placeholder: '30' },
      {
        name: 'arquivo_url',
        label: 'Arquivo do documento',
        type: 'file',
        accept: '.pdf,.png,.jpg,.jpeg,.webp',
        upload: {
          folder: 'documentos-rh',
          entityIdField: 'colaborador_id',
        },
        placeholder: 'PDF, foto ou imagem do documento',
      },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { value: 'vigente', label: 'Vigente' },
          { value: 'pendente', label: 'Pendente' },
          { value: 'vencido', label: 'Vencido' },
          { value: 'nao_se_aplica', label: 'Não se aplica' },
        ],
      },
      { name: 'obrigatorio', label: 'Obrigatório', type: 'checkbox', defaultValue: true },
      { name: 'observacoes', label: 'Observações', type: 'textarea', placeholder: 'Renovação, restrições, pendências ou contexto do documento' },
      { name: 'ativo', label: 'Ativo', type: 'checkbox', defaultValue: true },
    ],
  },
  eventos_rh: {
    title: 'Planejamento RH',
    subtitle: 'Férias, afastamentos, licenças e folgas programadas, separados da operação diária.',
    resource: 'eventos_rh',
    filters: [
      { name: 'tipo_evento', label: 'Tipo', type: 'text' },
      { name: 'status', label: 'Status', type: 'text' },
      { name: 'filial_id', label: 'Filial', type: 'select', relation: 'filiais', optionLabel: 'cidade' },
      {
        name: 'colaborador_id',
        label: 'Colaborador',
        type: 'select',
        relation: 'colaboradores',
        optionLabel: 'nome_completo',
        searchable: true,
        dependsOn: 'filial_id',
        dependsOnRelationField: 'filial_id',
      },
      {
        name: 'ativo',
        label: 'Ativo',
        type: 'select',
        options: [
          { value: 'true', label: 'Sim' },
          { value: 'false', label: 'Não' },
        ],
      },
    ],
    columns: [
      { key: 'colaborador_id', label: 'Colaborador', relation: 'colaboradores', optionLabel: 'nome_completo' },
      { key: 'filial_id', label: 'Filial', relation: 'filiais', optionLabel: 'cidade' },
      { key: 'tipo_evento', label: 'Tipo' },
      { key: 'data_inicio', label: 'Início' },
      { key: 'data_fim', label: 'Fim' },
      { key: 'status', label: 'Status' },
      { key: 'impacta_presenca', label: 'Impacta presença', type: 'boolean' },
    ],
    fields: [
      { name: 'filial_id', label: 'Filial', type: 'select', required: true, relation: 'filiais', optionLabel: 'cidade' },
      {
        name: 'colaborador_id',
        label: 'Colaborador',
        type: 'select',
        required: true,
        relation: 'colaboradores',
        optionLabel: 'nome_completo',
        searchable: true,
        dependsOn: 'filial_id',
        dependsOnRelationField: 'filial_id',
        requireDependsOn: true,
      },
      {
        name: 'tipo_evento',
        label: 'Tipo de evento',
        type: 'select',
        required: true,
        options: [
          { value: 'ferias', label: 'Férias' },
          { value: 'afastamento', label: 'Afastamento' },
          { value: 'licenca', label: 'Licença' },
          { value: 'atestado', label: 'Atestado' },
          { value: 'folga_programada', label: 'Folga programada' },
        ],
      },
      { name: 'data_inicio', label: 'Data início', type: 'date', required: true },
      { name: 'data_fim', label: 'Data fim', type: 'date', required: true },
      {
        name: 'status',
        label: 'Status do planejamento',
        type: 'select',
        required: true,
        defaultValue: 'planejado',
        options: [
          { value: 'planejado', label: 'Planejado' },
          { value: 'aprovado', label: 'Aprovado' },
          { value: 'em_andamento', label: 'Em andamento' },
          { value: 'concluido', label: 'Concluído' },
          { value: 'cancelado', label: 'Cancelado' },
        ],
      },
      { name: 'cobertura_colaborador_id', label: 'Cobertura por', type: 'select', relation: 'colaboradores', optionLabel: 'nome_completo' },
      { name: 'impacta_presenca', label: 'Impacta presença', type: 'checkbox', defaultValue: true },
      { name: 'dias_uteis', label: 'Dias úteis do evento', type: 'number', placeholder: '30', tooltip: 'Número de dias úteis contabilizados neste evento (férias, afastamento etc.)' },
      {
        name: 'abono_pecuniario',
        label: 'Abono pecuniário (1/3 das férias em dinheiro)',
        type: 'checkbox',
        defaultValue: false,
        visibleWhen: { field: 'tipo_evento', equals: 'ferias' },
        tooltip: 'O colaborador optou por vender até 1/3 das férias em dinheiro',
      },
      {
        name: 'parcela',
        label: 'Parcela das férias',
        type: 'select',
        visibleWhen: { field: 'tipo_evento', equals: 'ferias' },
        options: [
          { value: '1', label: '1ª parcela' },
          { value: '2', label: '2ª parcela' },
          { value: '3', label: '3ª parcela' },
        ],
        tooltip: 'Férias podem ser fracionadas em até 3 períodos pela CLT',
      },
      { name: 'observacoes', label: 'Observações', type: 'textarea', placeholder: 'Motivo, aprovação, cobertura ou contexto do evento RH' },
      { name: 'ativo', label: 'Ativo', type: 'checkbox', defaultValue: true },
    ],
  },
  veiculos: {
    title: 'Veículos',
    subtitle: 'Controle completo da frota: dados técnicos, documentação com vencimento e histórico de KM.',
    resource: 'veiculos',
    importer: {
      templateUrl: '/modelos/modelo_importacao_veiculos.csv',
      columns: [
        'filial',
        'placa',
        'marca',
        'modelo',
        'tipo',
        'tipo_veiculo',
        'ano_modelo',
        'cor',
        'chassi',
        'combustivel',
        'capacidade_tanque',
        'status',
        'odometro_atual',
        'km_proxima_revisao',
        'data_vencimento_crlv',
        'data_vencimento_seguro',
        'data_ultima_revisao',
        'descricao',
      ],
      acceptsExcel: true,
      tipoOptions: ['rota', 'transferencia', 'diaria', 'multidia'],
      mapping: [
        { csv: 'filial', field: 'Filial', help: 'Cidade ou cidade/UF (ex: Belém/PA). Obrigatório.' },
        { csv: 'placa', field: 'Placa', help: 'Identificador único. Obrigatório. Combo cavalo/carreta aceito: "ABC1D23/XYZ4W56".' },
        { csv: 'marca', field: 'Marca', help: 'Ex: Volvo, Scania. Vazio vira "—".' },
        { csv: 'modelo', field: 'Modelo', help: 'Ex: FH 540. Vazio ou "0" vira "—".' },
        { csv: 'tipo', field: 'Tipo operacional', help: 'rota, transferencia, diaria ou multidia.' },
        { csv: 'tipo_veiculo', field: 'Categoria do veículo', help: 'Texto livre: cavalo/carreta, truck, toco, 3/4, van, utilitario...' },
        { csv: 'ano_modelo', field: 'Ano modelo', help: 'Número (ex: 2026).' },
        { csv: 'cor', field: 'Cor', help: 'Texto livre.' },
        { csv: 'chassi', field: 'Chassi', help: 'Texto livre (17 caracteres no padrão).' },
        { csv: 'combustivel', field: 'Combustível', help: 'diesel, gasolina, flex, etanol, gnv, eletrico.' },
        { csv: 'capacidade_tanque', field: 'Capacidade tanque (L)', help: 'Número decimal.' },
        { csv: 'status', field: 'Status', help: 'ativo, manutencao ou inativo. Padrão: ativo.' },
        { csv: 'odometro_atual', field: 'Odômetro atual (km)', help: 'Número inteiro. Vazio = 0.' },
        { csv: 'km_proxima_revisao', field: 'KM próxima revisão', help: 'Número inteiro.' },
        { csv: 'data_vencimento_crlv', field: 'Vencimento CRLV', help: 'AAAA-MM-DD ou DD/MM/AAAA. "0" ou vazio = sem data.' },
        { csv: 'data_vencimento_seguro', field: 'Vencimento seguro', help: 'AAAA-MM-DD ou DD/MM/AAAA.' },
        { csv: 'data_ultima_revisao', field: 'Data última revisão', help: 'AAAA-MM-DD ou DD/MM/AAAA.' },
        { csv: 'descricao', field: 'Observações', help: 'Texto livre.' },
      ],
    },
    filters: [
      { name: 'placa', label: 'Placa', type: 'text' },
      { name: 'chassi', label: 'Chassi', type: 'text' },
      { name: 'marca', label: 'Marca', type: 'text' },
      { name: 'modelo', label: 'Modelo', type: 'text' },
      { name: 'filial_id', label: 'Filial', type: 'select', relation: 'filiais', optionLabel: 'cidade' },
      {
        name: 'tipo',
        label: 'Tipo operacional',
        type: 'select',
        options: [
          { value: 'rota', label: 'Rota' },
          { value: 'transferencia', label: 'Transferência' },
          { value: 'diaria', label: 'Diária' },
          { value: 'multidia', label: 'Multidia' },
        ],
      },
      { name: 'tipo_veiculo', label: 'Categoria', type: 'text' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { value: 'ativo', label: 'Ativo' },
          { value: 'manutencao', label: 'Manutenção' },
          { value: 'inativo', label: 'Inativo' },
        ],
      },
    ],
    columns: [
      { key: 'placa', label: 'Placa' },
      { key: 'marca', label: 'Marca' },
      { key: 'modelo', label: 'Modelo' },
      { key: 'tipo', label: 'Tipo operacional' },
      { key: 'tipo_veiculo', label: 'Categoria' },
      { key: 'filial_id', label: 'Filial', relation: 'filiais', optionLabel: 'cidade' },
      { key: 'status', label: 'Status' },
      { key: 'odometro_atual', label: 'Odômetro (km)' },
      { key: 'data_vencimento_crlv', label: 'Venc. CRLV', type: 'date' },
      { key: 'data_vencimento_seguro', label: 'Venc. Seguro', type: 'date' },
    ],
    fields: [
      { name: 'filial_id', label: 'Filial', type: 'select', required: true, relation: 'filiais', optionLabel: 'cidade' },
      { name: 'placa', label: 'Placa', type: 'text', required: true, placeholder: 'ABC1D23' },
      { name: 'chassi', label: 'Chassi', type: 'text', placeholder: '17 caracteres' },
      { name: 'marca', label: 'Marca', type: 'text', required: true, placeholder: 'Ex.: Volkswagen' },
      { name: 'modelo', label: 'Modelo', type: 'text', required: true, placeholder: 'Ex.: Saveiro' },
      { name: 'ano_modelo', label: 'Ano modelo', type: 'number', placeholder: '2026' },
      { name: 'cor', label: 'Cor', type: 'text', placeholder: 'Ex.: Branco' },
      {
        name: 'tipo',
        label: 'Tipo operacional',
        type: 'select',
        tooltip: 'Como o veículo é usado na operação',
        options: [
          { value: 'rota', label: 'Rota' },
          { value: 'transferencia', label: 'Transferência' },
          { value: 'diaria', label: 'Diária' },
          { value: 'multidia', label: 'Multidia' },
        ],
      },
      {
        name: 'tipo_veiculo',
        label: 'Categoria do veículo',
        type: 'select',
        tooltip: 'Categoria física do veículo',
        options: [
          { value: 'utilitario', label: 'Utilitário' },
          { value: 'caminhao_leve', label: 'Caminhão leve' },
          { value: 'caminhao_medio', label: 'Caminhão médio' },
          { value: 'caminhao_pesado', label: 'Caminhão pesado' },
          { value: 'van', label: 'Van / Furgão' },
          { value: 'passeio', label: 'Passeio' },
          { value: 'moto', label: 'Moto' },
          { value: 'outro', label: 'Outro' },
        ],
      },
      {
        name: 'combustivel',
        label: 'Combustível',
        type: 'select',
        options: [
          { value: 'diesel', label: 'Diesel' },
          { value: 'gasolina', label: 'Gasolina' },
          { value: 'flex', label: 'Flex' },
          { value: 'etanol', label: 'Etanol' },
          { value: 'gnv', label: 'GNV' },
          { value: 'eletrico', label: 'Elétrico' },
        ],
      },
      { name: 'capacidade_tanque', label: 'Capacidade do tanque (L)', type: 'number', placeholder: '80' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        defaultValue: 'ativo',
        options: [
          { value: 'ativo', label: 'Ativo' },
          { value: 'manutencao', label: 'Em manutenção' },
          { value: 'inativo', label: 'Inativo' },
        ],
      },
      { name: 'odometro_atual', label: 'Odômetro atual (km)', type: 'number', defaultValue: 0, placeholder: '0' },
      { name: 'km_proxima_revisao', label: 'KM próxima revisão', type: 'number', placeholder: '0' },
      { name: 'data_vencimento_crlv', label: 'Vencimento CRLV', type: 'date', tooltip: 'Data de vencimento do Certificado de Registro e Licenciamento' },
      { name: 'data_vencimento_seguro', label: 'Vencimento seguro', type: 'date' },
      { name: 'data_ultima_revisao', label: 'Data última revisão', type: 'date' },
      { name: 'descricao', label: 'Observações', type: 'textarea', placeholder: 'Estado geral, uso, particularidades' },
    ],
  },
  rotas_carregamento: {
    title: 'Referências de carregamento',
    subtitle: 'Tabela de apoio da referência operacional usada no turno. Pode ser só um nome como Área E, Mega ou Cachoeirinha.',
    resource: 'rotas_carregamento',
    filters: [
      { name: 'nome', label: 'Referência', type: 'text' },
      { name: 'origem', label: 'Origem', type: 'text' },
      { name: 'destino', label: 'Destino', type: 'text' },
      { name: 'filial_id', label: 'Filial', type: 'select', relation: 'filiais', optionLabel: 'cidade' },
      {
        name: 'ativo',
        label: 'Ativa',
        type: 'select',
        options: [
          { value: 'true', label: 'Sim' },
          { value: 'false', label: 'Não' },
        ],
      },
    ],
    columns: [
      { key: 'nome', label: 'Referência' },
      { key: 'codigo', label: 'Código' },
      { key: 'origem', label: 'Origem' },
      { key: 'destino', label: 'Destino' },
      { key: 'filial_id', label: 'Filial', relation: 'filiais', optionLabel: 'cidade' },
      { key: 'ativo', label: 'Ativa', type: 'boolean' },
    ],
    fields: [
      { name: 'filial_id', label: 'Filial', type: 'select', required: true, relation: 'filiais', optionLabel: 'cidade' },
      {
        name: 'codigo',
        label: 'Código',
        type: 'text',
        placeholder: 'Preenchido pela filial, mas pode editar',
        autoFill: {
          triggerField: 'filial_id',
          relation: 'filiais',
          sourceField: 'codigo',
        },
      },
      { name: 'nome', label: 'Nome operacional', type: 'text', required: true, placeholder: 'Ex.: Área E, Mega, Cachoeirinha' },
      { name: 'origem', label: 'Origem opcional', type: 'text', placeholder: 'Preencha só se fizer sentido' },
      { name: 'destino', label: 'Destino opcional', type: 'text', placeholder: 'Preencha só se fizer sentido' },
      { name: 'observacoes', label: 'Observações', type: 'textarea', placeholder: 'Detalhes complementares da referência operacional' },
      { name: 'ativo', label: 'Ativa', type: 'checkbox', defaultValue: true },
    ],
  },
  veiculos_carregamento: {
    title: 'Veículos de carregamento',
    subtitle: 'Cadastro dos caminhões terceiros usados no carregamento por base e rota padrão.',
    resource: 'veiculos_carregamento',
    filters: [
      { name: 'placa', label: 'Placa', type: 'text' },
      { name: 'transportadora', label: 'Transportadora', type: 'text' },
      { name: 'tipo_veiculo', label: 'Tipo', type: 'text' },
      { name: 'filial_id', label: 'Filial', type: 'select', relation: 'filiais', optionLabel: 'cidade' },
      {
        name: 'ativo',
        label: 'Ativo',
        type: 'select',
        options: [
          { value: 'true', label: 'Sim' },
          { value: 'false', label: 'Não' },
        ],
      },
    ],
    columns: [
      { key: 'placa', label: 'Placa' },
      { key: 'transportadora', label: 'Transportadora' },
      { key: 'tipo_veiculo', label: 'Tipo' },
      { key: 'rota_id', label: 'Referência', relation: 'rotas_carregamento', optionLabel: 'nome' },
      { key: 'filial_id', label: 'Filial', relation: 'filiais', optionLabel: 'cidade' },
      { key: 'ativo', label: 'Ativo', type: 'boolean' },
    ],
    fields: [
      { name: 'filial_id', label: 'Filial', type: 'select', required: true, relation: 'filiais', optionLabel: 'cidade' },
      { name: 'rota_id', label: 'Referência padrão', type: 'select', relation: 'rotas_carregamento', optionLabel: 'nome' },
      { name: 'placa', label: 'Placa', type: 'text', required: true, placeholder: 'ABC1D23' },
      { name: 'transportadora', label: 'Transportadora', type: 'text', required: true, placeholder: 'Nome da transportadora' },
      { name: 'tipo_veiculo', label: 'Tipo de veículo', type: 'text', placeholder: 'Ex.: Truck, Cavalo, Bi-trem' },
      { name: 'capacidade_cilindros', label: 'Capacidade de cilindros', type: 'number', placeholder: '0' },
      { name: 'observacoes', label: 'Observações', type: 'textarea', placeholder: 'Restrições ou observações do caminhão' },
      { name: 'ativo', label: 'Ativo', type: 'checkbox', defaultValue: true },
    ],
  },
  motivos_parada_carregamento: {
    title: 'Motivos de parada',
    subtitle: 'Padronização dos motivos usados para medir tempo parado durante o carregamento.',
    resource: 'motivos_parada_carregamento',
    filters: [
      { name: 'descricao', label: 'Motivo', type: 'text' },
      {
        name: 'ativo',
        label: 'Ativo',
        type: 'select',
        options: [
          { value: 'true', label: 'Sim' },
          { value: 'false', label: 'Não' },
        ],
      },
    ],
    columns: [
      { key: 'descricao', label: 'Motivo' },
      { key: 'ordem', label: 'Ordem' },
      { key: 'exige_observacao', label: 'Exige observação', type: 'boolean' },
      { key: 'ativo', label: 'Ativo', type: 'boolean' },
    ],
    fields: [
      { name: 'descricao', label: 'Motivo', type: 'text', required: true, placeholder: 'Ex.: Problema no caminhão' },
      { name: 'ordem', label: 'Ordem', type: 'number', defaultValue: 0, placeholder: '0' },
      { name: 'exige_observacao', label: 'Exige observação', type: 'checkbox' },
      { name: 'ativo', label: 'Ativo', type: 'checkbox', defaultValue: true },
    ],
  },
  bonificacao_metricas: {
    title: 'Métricas de bonificação',
    subtitle: 'Defina e ajuste os critérios e valores que compõem a bonificação mensal.',
    resource: 'bonificacao_metricas',
    filters: [
      { name: 'nome', label: 'Métrica', type: 'text' },
      {
        name: 'categoria',
        label: 'Categoria',
        type: 'select',
        options: [
          { value: 'individual', label: 'Individual' },
          { value: 'coletivo', label: 'Coletivo' },
        ],
      },
      {
        name: 'ativo',
        label: 'Ativo',
        type: 'select',
        options: [
          { value: 'true', label: 'Sim' },
          { value: 'false', label: 'Não' },
        ],
      },
    ],
    columns: [
      { key: 'nome', label: 'Métrica' },
      { key: 'categoria', label: 'Categoria' },
      { key: 'valor', label: 'Valor (R$)' },
      { key: 'ordem', label: 'Ordem' },
      { key: 'ativo', label: 'Ativo', type: 'boolean' },
    ],
    fields: [
      { name: 'nome', label: 'Nome da métrica', type: 'text', required: true, placeholder: 'Ex.: Presença e compromisso' },
      {
        name: 'categoria',
        label: 'Categoria',
        type: 'select',
        required: true,
        defaultValue: 'individual',
        options: [
          { value: 'individual', label: 'Individual' },
          { value: 'coletivo', label: 'Coletivo' },
        ],
      },
      { name: 'valor', label: 'Valor da bonificação (R$)', type: 'number', required: true, defaultValue: 0, placeholder: '100' },
      { name: 'ordem', label: 'Ordem de exibição', type: 'number', defaultValue: 0, placeholder: '0' },
      { name: 'descricao', label: 'Descrição', type: 'textarea', placeholder: 'Regra objetiva para considerar a métrica atingida' },
      { name: 'ativo', label: 'Ativa', type: 'checkbox', defaultValue: true },
    ],
  },
  pedidos_compra: {
    title: 'Pedidos de compra',
    subtitle: 'Registre pedidos de compra por base, com itens, fornecedor, forma de pagamento e prazo. Gere PDF para aprovação e controle.',
    resource: 'pedidos_compra',
    createScope: 'create.pedidos_compra',
    filters: [
      { name: 'filial_id', label: 'Filial', type: 'select', relation: 'filiais', optionLabel: 'cidade' },
      { name: 'numero_pedido', label: 'Número', type: 'text' },
      { name: 'fornecedor', label: 'Fornecedor', type: 'text' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { value: 'rascunho', label: 'Rascunho' },
          { value: 'pendente_aprovacao', label: 'Pendente aprovação' },
          { value: 'aprovado', label: 'Aprovado' },
          { value: 'em_compra', label: 'Em compra' },
          { value: 'recebido', label: 'Recebido' },
          { value: 'cancelado', label: 'Cancelado' },
        ],
      },
      {
        name: 'ativo',
        label: 'Ativo',
        type: 'select',
        options: [
          { value: 'true', label: 'Sim' },
          { value: 'false', label: 'Não' },
        ],
      },
    ],
    columns: [
      { key: 'numero_pedido', label: 'Número' },
      { key: 'filial_id', label: 'Filial', relation: 'filiais', optionLabel: 'cidade' },
      { key: 'data_pedido', label: 'Data' },
      { key: 'data_necessidade', label: 'Precisa até' },
      { key: 'fornecedor', label: 'Fornecedor' },
      { key: 'status', label: 'Status' },
      { key: 'forma_pagamento', label: 'Pagamento' },
      { key: 'valor_total_calculado', label: 'Total (R$)', type: 'currency' },
      { key: 'criado_por_nome', label: 'Criado por' },
    ],
    fields: [
      { name: 'filial_id', label: 'Filial', type: 'select', required: true, relation: 'filiais', optionLabel: 'cidade' },
      { name: 'data_pedido', label: 'Data do pedido', type: 'date', required: true },
      { name: 'data_necessidade', label: 'Data de necessidade', type: 'date', placeholder: 'Quando precisa ter o material' },
      { name: 'fornecedor', label: 'Fornecedor', type: 'text', placeholder: 'Nome do fornecedor ou loja' },
      {
        name: 'forma_pagamento',
        label: 'Forma de pagamento',
        type: 'select',
        options: [
          { value: 'dinheiro', label: 'Dinheiro' },
          { value: 'pix', label: 'PIX' },
          { value: 'cartao_debito', label: 'Cartão débito' },
          { value: 'cartao_credito', label: 'Cartão crédito' },
          { value: 'boleto', label: 'Boleto' },
          { value: 'credito_fornecedor', label: 'Crédito fornecedor' },
        ],
      },
      { name: 'prazo_pagamento', label: 'Prazo de pagamento', type: 'text', placeholder: 'Ex.: à vista, 30 dias, 15/30/45' },
      { name: 'centro_custo', label: 'Centro de custo', type: 'text', placeholder: 'Ex.: manutenção, limpeza, operação' },
      {
        name: 'criado_por',
        label: 'Criado por (colaborador)',
        type: 'select',
        relation: 'colaboradores',
        optionLabel: 'nome_completo',
        searchable: true,
        dependsOn: 'filial_id',
        dependsOnRelationField: 'filial_id',
      },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        defaultValue: 'rascunho',
        options: [
          { value: 'rascunho', label: 'Rascunho' },
          { value: 'pendente_aprovacao', label: 'Pendente aprovação' },
          { value: 'aprovado', label: 'Aprovado' },
          { value: 'em_compra', label: 'Em compra' },
          { value: 'recebido', label: 'Recebido' },
          { value: 'cancelado', label: 'Cancelado' },
        ],
      },
      { name: 'observacoes', label: 'Observações gerais', type: 'textarea', placeholder: 'Instruções, urgência, contexto do pedido' },
      { name: 'ativo', label: 'Ativo', type: 'checkbox', defaultValue: true },
    ],
  },
  pedidos_compra_itens: {
    title: 'Itens do pedido',
    subtitle: 'Adicione os itens do pedido selecionado com quantidade, valor unitário e categoria.',
    resource: 'pedidos_compra_itens',
    createScope: 'create.pedidos_compra',
    filters: [
      { name: 'filial_id', label: 'Filial', type: 'select', relation: 'filiais', optionLabel: 'cidade' },
      { name: 'descricao', label: 'Item', type: 'text' },
      {
        name: 'categoria',
        label: 'Categoria',
        type: 'select',
        options: [
          { value: 'limpeza', label: 'Limpeza' },
          { value: 'manutencao', label: 'Manutenção' },
          { value: 'epi', label: 'EPI' },
          { value: 'escritorio', label: 'Escritório' },
          { value: 'alimentacao', label: 'Alimentação' },
          { value: 'combustivel', label: 'Combustível' },
          { value: 'informatica', label: 'Informática' },
          { value: 'uniforme', label: 'Uniforme' },
          { value: 'ferramentas', label: 'Ferramentas' },
          { value: 'outro', label: 'Outro' },
        ],
      },
      {
        name: 'ativo',
        label: 'Ativo',
        type: 'select',
        options: [
          { value: 'true', label: 'Sim' },
          { value: 'false', label: 'Não' },
        ],
      },
    ],
    columns: [
      { key: 'categoria', label: 'Categoria' },
      { key: 'descricao', label: 'Item' },
      { key: 'quantidade', label: 'Qtd' },
      { key: 'unidade', label: 'Un.' },
      { key: 'valor_unitario', label: 'Valor unit.', type: 'currency' },
      { key: 'valor_total', label: 'Total', type: 'currency' },
      { key: 'observacoes', label: 'Obs.' },
      { key: 'ativo', label: 'Ativo', type: 'boolean' },
    ],
    fields: [
      { name: 'filial_id', label: 'Filial', type: 'select', required: true, relation: 'filiais', optionLabel: 'cidade' },
      {
        name: 'pedido_id',
        label: 'Pedido',
        type: 'select',
        required: true,
        relation: 'pedidos_compra',
        optionLabel: 'numero_pedido',
        searchable: true,
        dependsOn: 'filial_id',
        dependsOnRelationField: 'filial_id',
        requireDependsOn: true,
      },
      {
        name: 'categoria',
        label: 'Categoria',
        type: 'select',
        required: true,
        defaultValue: 'outro',
        options: [
          { value: 'limpeza', label: 'Limpeza' },
          { value: 'manutencao', label: 'Manutenção' },
          { value: 'epi', label: 'EPI' },
          { value: 'escritorio', label: 'Escritório' },
          { value: 'alimentacao', label: 'Alimentação' },
          { value: 'combustivel', label: 'Combustível' },
          { value: 'informatica', label: 'Informática' },
          { value: 'uniforme', label: 'Uniforme' },
          { value: 'ferramentas', label: 'Ferramentas' },
          { value: 'outro', label: 'Outro' },
        ],
      },
      { name: 'descricao', label: 'Descrição do item', type: 'text', required: true, placeholder: 'Ex.: Luva de borracha, Vassoura, Papel toalha' },
      {
        name: 'unidade',
        label: 'Unidade',
        type: 'select',
        required: true,
        defaultValue: 'un',
        options: [
          { value: 'un', label: 'UN (unidade)' },
          { value: 'kg', label: 'KG (quilograma)' },
          { value: 'l', label: 'L (litro)' },
          { value: 'cx', label: 'CX (caixa)' },
          { value: 'pct', label: 'PCT (pacote)' },
          { value: 'm', label: 'M (metro)' },
          { value: 'par', label: 'PAR' },
          { value: 'rolo', label: 'Rolo' },
        ],
      },
      { name: 'quantidade', label: 'Quantidade', type: 'number', required: true, defaultValue: 1, placeholder: '1' },
      { name: 'valor_unitario', label: 'Valor unitário (R$)', type: 'number', required: true, defaultValue: 0, placeholder: '0,00' },
      { name: 'observacoes', label: 'Observações do item', type: 'textarea', placeholder: 'Ex.: marca preferencial, tamanho, especificação' },
      { name: 'ativo', label: 'Ativo', type: 'checkbox', defaultValue: true },
    ],
  },

  // ─── FROTA: ABASTECIMENTOS ────────────────────────────────────────────────
  veiculos_abastecimentos: {
    title: 'Abastecimentos',
    subtitle: 'Registro de abastecimentos de combustível por veículo. O valor total é calculado automaticamente.',
    resource: 'veiculos_abastecimentos',
    createScope: 'create.abastecimentos',
    filters: [
      { name: 'filial_id', label: 'Filial', type: 'select', relation: 'filiais', optionLabel: 'cidade' },
      { name: 'veiculo_id', label: 'Veículo', type: 'select', relation: 'veiculos', optionLabel: 'placa', searchable: true, dependsOn: 'filial_id', dependsOnRelationField: 'filial_id' },
      { name: 'data_abastecimento', label: 'Data', type: 'date' },
      { name: 'tipo_combustivel', label: 'Combustível', type: 'select', options: [
        { value: 'diesel', label: 'Diesel' },
        { value: 'diesel_s10', label: 'Diesel S10' },
        { value: 'gasolina', label: 'Gasolina' },
        { value: 'flex', label: 'Flex / Etanol' },
        { value: 'gnv', label: 'GNV' },
      ]},
      { name: 'ativo', label: 'Ativo', type: 'select', options: [{ value: 'true', label: 'Sim' }, { value: 'false', label: 'Não' }] },
    ],
    columns: [
      { key: 'numero_solicitacao', label: 'N° Solicitação' },
      { key: 'data_abastecimento', label: 'Data', type: 'date' },
      { key: 'veiculo_id', label: 'Veículo', relation: 'veiculos', optionLabel: 'placa' },
      { key: 'tipo_combustivel', label: 'Combustível' },
      { key: 'odometro_km', label: 'Km' },
      { key: 'litros', label: 'Litros' },
      { key: 'valor_litro', label: 'R$/L', type: 'currency' },
      { key: 'valor_total', label: 'Total', type: 'currency' },
      { key: 'fornecedor', label: 'Posto / Fornecedor' },
      { key: 'status', label: 'Situação' },
    ],
    fields: [
      { name: 'filial_id', label: 'Filial', type: 'select', required: true, relation: 'filiais', optionLabel: 'cidade', tooltip: 'Filial à qual o veículo pertence' },
      { name: 'veiculo_id', label: 'Veículo', type: 'select', required: true, relation: 'veiculos', optionLabel: 'placa', searchable: true, dependsOn: 'filial_id', dependsOnRelationField: 'filial_id', tooltip: 'Placa do veículo abastecido' },
      { name: 'data_abastecimento', label: 'Data do abastecimento', type: 'date', required: true, tooltip: 'Data em que o abastecimento ocorreu' },
      { name: 'odometro_km', label: 'Odômetro (km)', type: 'number', required: true, placeholder: 'Ex.: 125000', tooltip: 'Leitura do hodômetro no momento do abastecimento' },
      { name: 'tipo_combustivel', label: 'Tipo de combustível', type: 'select', required: true, defaultValue: 'diesel', options: [
        { value: 'diesel', label: 'Diesel' },
        { value: 'diesel_s10', label: 'Diesel S10' },
        { value: 'gasolina', label: 'Gasolina' },
        { value: 'flex', label: 'Flex / Etanol' },
        { value: 'gnv', label: 'GNV' },
      ], tooltip: 'Tipo do combustível abastecido' },
      { name: 'litros', label: 'Litros abastecidos', type: 'number', required: true, placeholder: 'Ex.: 120.5', tooltip: 'Quantidade em litros mostrada na bomba' },
      { name: 'valor_litro', label: 'Preço por litro (R$)', type: 'number', required: true, placeholder: 'Ex.: 6.299', tooltip: 'Valor unitário do litro no momento do abastecimento' },
      { name: 'fornecedor', label: 'Posto / Fornecedor', type: 'text', placeholder: 'Ex.: Posto Shell Av. Brasil', tooltip: 'Nome do posto ou fornecedor de combustível' },
      { name: 'numero_nota', label: 'Nº da nota fiscal', type: 'text', placeholder: 'Ex.: 000123', tooltip: 'Número da nota fiscal ou cupom fiscal do abastecimento' },
      { name: 'motorista_id', label: 'Motorista', type: 'select', relation: 'colaboradores', optionLabel: 'nome_completo', searchable: true, tooltip: 'Colaborador que realizou o abastecimento' },
      { name: 'observacoes', label: 'Observações', type: 'textarea', placeholder: 'Ex.: Tanque completo, sem reserva' },
      { name: 'ativo', label: 'Ativo', type: 'checkbox', defaultValue: true },
    ],
  },

  // ─── FROTA: PNEUS ─────────────────────────────────────────────────────────
  veiculos_pneus: {
    title: 'Controle de Pneus',
    subtitle: 'Controle de pneus por posição em cada veículo. Acompanhe desgaste, vida útil e programação de rodízios.',
    resource: 'veiculos_pneus',
    createScope: 'create.pneus',
    filters: [
      { name: 'filial_id', label: 'Filial', type: 'select', relation: 'filiais', optionLabel: 'cidade' },
      { name: 'veiculo_id', label: 'Veículo', type: 'select', relation: 'veiculos', optionLabel: 'placa', searchable: true, dependsOn: 'filial_id', dependsOnRelationField: 'filial_id' },
      { name: 'status', label: 'Status', type: 'select', options: [
        { value: 'ativo', label: 'Ativo' },
        { value: 'rodiziar', label: 'Rodiziar' },
        { value: 'trocar', label: 'Trocar' },
        { value: 'sucata', label: 'Sucata' },
      ]},
      { name: 'ativo', label: 'Ativo', type: 'select', options: [{ value: 'true', label: 'Sim' }, { value: 'false', label: 'Não' }] },
    ],
    columns: [
      { key: 'numero_solicitacao', label: 'N° Solicitação' },
      { key: 'veiculo_id', label: 'Veículo', relation: 'veiculos', optionLabel: 'placa' },
      { key: 'posicao', label: 'Posição' },
      { key: 'marca', label: 'Marca' },
      { key: 'medida', label: 'Medida' },
      { key: 'status', label: 'Condição' },
      { key: 'status_aprovacao', label: 'Aprovação' },
      { key: 'vida', label: 'Vida' },
      { key: 'odometro_instalacao', label: 'Km instalação' },
      { key: 'data_instalacao', label: 'Instalação', type: 'date' },
    ],
    fields: [
      { name: 'filial_id', label: 'Filial', type: 'select', required: true, relation: 'filiais', optionLabel: 'cidade', tooltip: 'Filial à qual o veículo pertence' },
      { name: 'veiculo_id', label: 'Veículo', type: 'select', required: true, relation: 'veiculos', optionLabel: 'placa', searchable: true, dependsOn: 'filial_id', dependsOnRelationField: 'filial_id', tooltip: 'Placa do veículo' },
      { name: 'posicao', label: 'Posição', type: 'text', required: true, placeholder: 'Ex.: DD1, DE1, TE2, estepe', tooltip: 'Posição no veículo: DD=dianteiro direito, TE=traseiro esquerdo; número indica eixo. Ex.: DD1, TE2, estepe' },
      { name: 'marca', label: 'Marca', type: 'text', placeholder: 'Ex.: Bridgestone, Goodyear, Pirelli', tooltip: 'Fabricante do pneu' },
      { name: 'modelo', label: 'Modelo', type: 'text', placeholder: 'Ex.: R283A, G567', tooltip: 'Modelo/linha do pneu' },
      { name: 'medida', label: 'Medida', type: 'text', placeholder: 'Ex.: 295/80 R22.5', tooltip: 'Medida do pneu conforme marcação na lateral: largura/perfil Raro' },
      { name: 'numero_serie', label: 'Nº de série', type: 'text', placeholder: 'Ex.: BR20230101', tooltip: 'Número de série ou identificador único do pneu para rastreio' },
      { name: 'dot', label: 'DOT', type: 'text', placeholder: 'Ex.: 2523 (semana 25 de 2023)', tooltip: 'Código DOT: identifica fabricante, tamanho e data de fabricação. Os 4 últimos dígitos = semana+ano' },
      { name: 'data_instalacao', label: 'Data de instalação', type: 'date', tooltip: 'Data em que o pneu foi montado no veículo' },
      { name: 'odometro_instalacao', label: 'Km na instalação', type: 'number', placeholder: 'Ex.: 120000', tooltip: 'Hodômetro no momento da instalação. Usado para calcular km rodados com este pneu' },
      { name: 'odometro_atual', label: 'Km atual', type: 'number', placeholder: 'Ex.: 145000', tooltip: 'Hodômetro atual para cálculo de km percorridos' },
      { name: 'vida', label: 'Vida útil', type: 'select', defaultValue: 1, options: [
        { value: 1, label: '1 — Novo' },
        { value: 2, label: '2 — Recapado 1x' },
        { value: 3, label: '3 — Recapado 2x' },
        { value: 4, label: '4 — Recapado 3x' },
      ], tooltip: 'Número de vidas: pneu novo = 1; cada recapagem adiciona 1 vida' },
      { name: 'status', label: 'Status', type: 'select', required: true, defaultValue: 'ativo', options: [
        { value: 'ativo', label: 'Ativo — em uso' },
        { value: 'rodiziar', label: 'Rodiziar — troca de posição programada' },
        { value: 'trocar', label: 'Trocar — substituição necessária' },
        { value: 'sucata', label: 'Sucata — descartado' },
      ], tooltip: 'Estado atual do pneu. Altere para "Rodiziar" ou "Trocar" para gerar alerta no painel' },
      { name: 'observacoes', label: 'Observações', type: 'textarea', placeholder: 'Ex.: pneu com desgaste irregular no ombro, verificar alinhamento' },
      { name: 'ativo', label: 'Ativo', type: 'checkbox', defaultValue: true },
    ],
  },

  // ─── FROTA: MANUTENÇÕES ───────────────────────────────────────────────────
  manutencoes: {
    title: 'Manutenções',
    subtitle: 'Ordens de Serviço de manutenção de veículos. Fluxo: Aberta → Aguardando aprovação → Aprovada → Em execução → Concluída.',
    resource: 'manutencoes',
    createScope: 'create.manutencoes',
    filters: [
      { name: 'filial_id', label: 'Filial', type: 'select', relation: 'filiais', optionLabel: 'cidade' },
      { name: 'veiculo_id', label: 'Veículo', type: 'select', relation: 'veiculos', optionLabel: 'placa', searchable: true },
      { name: 'status', label: 'Status', type: 'select', options: [
        { value: 'aberta', label: 'Aberta' },
        { value: 'aguardando_aprovacao', label: 'Aguardando aprovação' },
        { value: 'aprovada', label: 'Aprovada' },
        { value: 'em_execucao', label: 'Em execução' },
        { value: 'concluida', label: 'Concluída' },
        { value: 'cancelada', label: 'Cancelada' },
        { value: 'reprovada', label: 'Reprovada' },
      ]},
      { name: 'tipo', label: 'Tipo', type: 'select', options: [
        { value: 'preventiva', label: 'Preventiva' },
        { value: 'corretiva', label: 'Corretiva' },
        { value: 'preditiva', label: 'Preditiva' },
        { value: 'recall', label: 'Recall' },
      ]},
      { name: 'prioridade', label: 'Prioridade', type: 'select', options: [
        { value: 'critica', label: 'Crítica' },
        { value: 'alta', label: 'Alta' },
        { value: 'normal', label: 'Normal' },
        { value: 'baixa', label: 'Baixa' },
      ]},
      { name: 'ativo', label: 'Ativo', type: 'select', options: [{ value: 'true', label: 'Sim' }, { value: 'false', label: 'Não' }] },
    ],
    columns: [
      { key: 'numero_solicitacao', label: 'N° Solicitação' },
      { key: 'data_abertura', label: 'Abertura', type: 'date' },
      { key: 'veiculo_id', label: 'Veículo', relation: 'veiculos', optionLabel: 'placa' },
      { key: 'tipo', label: 'Tipo' },
      { key: 'prioridade', label: 'Prioridade' },
      { key: 'titulo', label: 'Título' },
      { key: 'status', label: 'Status' },
      { key: 'valor_estimado', label: 'Estimado', type: 'currency' },
      { key: 'valor_final', label: 'Final', type: 'currency' },
    ],
    fields: [
      { name: 'filial_id', label: 'Filial', type: 'select', required: true, relation: 'filiais', optionLabel: 'cidade', tooltip: 'Filial responsável por esta OS' },
      { name: 'veiculo_id', label: 'Veículo', type: 'select', required: true, relation: 'veiculos', optionLabel: 'placa', searchable: true, dependsOn: 'filial_id', dependsOnRelationField: 'filial_id', tooltip: 'Veículo que está sendo mantido' },
      { name: 'tipo', label: 'Tipo de manutenção', type: 'select', required: true, defaultValue: 'corretiva', options: [
        { value: 'preventiva', label: 'Preventiva — programada por km/tempo' },
        { value: 'corretiva', label: 'Corretiva — quebra ou falha' },
        { value: 'preditiva', label: 'Preditiva — diagnóstico técnico' },
        { value: 'recall', label: 'Recall — determinação do fabricante' },
      ], tooltip: 'Preventiva=programada; Corretiva=quebra; Preditiva=inspeção técnica; Recall=fabricante' },
      { name: 'prioridade', label: 'Prioridade', type: 'select', required: true, defaultValue: 'normal', options: [
        { value: 'critica', label: 'Crítica — veículo parado / risco de acidente' },
        { value: 'alta', label: 'Alta — urgente, resolve em 24h' },
        { value: 'normal', label: 'Normal — rotina, até 5 dias úteis' },
        { value: 'baixa', label: 'Baixa — pode aguardar programação' },
      ], tooltip: 'Define a urgência. Crítica e Alta geram destaque no painel e notificam o aprovador' },
      { name: 'titulo', label: 'Título da OS', type: 'text', required: true, placeholder: 'Ex.: Troca de freios dianteiros', tooltip: 'Resumo do serviço — aparece nas listagens e relatórios' },
      { name: 'descricao', label: 'Descrição detalhada', type: 'textarea', placeholder: 'Descreva o problema, sintomas e o que precisa ser feito', tooltip: 'Descrição completa para o mecânico/oficina entender o escopo' },
      { name: 'data_abertura', label: 'Data de abertura', type: 'date', required: true, tooltip: 'Data em que o problema foi identificado' },
      { name: 'data_previsao', label: 'Previsão de conclusão', type: 'date', tooltip: 'Data estimada para entrega do veículo' },
      { name: 'odometro_entrada', label: 'Km na entrada', type: 'number', placeholder: 'Ex.: 128500', tooltip: 'Hodômetro do veículo ao entrar na oficina' },
      { name: 'oficina', label: 'Oficina / Fornecedor', type: 'text', placeholder: 'Ex.: Oficina Central Gold — Uberlândia', tooltip: 'Nome da oficina ou mecânico responsável pelo serviço' },
      { name: 'solicitado_por', label: 'Solicitado por', type: 'select', relation: 'colaboradores', optionLabel: 'nome_completo', searchable: true, tooltip: 'Colaborador que identificou o problema e abriu a OS' },
      { name: 'responsavel_id', label: 'Responsável', type: 'select', relation: 'colaboradores', optionLabel: 'nome_completo', searchable: true, tooltip: 'Colaborador responsável por acompanhar e fechar esta OS' },
      { name: 'valor_estimado', label: 'Valor estimado (R$)', type: 'number', defaultValue: 0, placeholder: '0,00', tooltip: 'Orçamento inicial da oficina. Necessário para aprovação quando há limite de valor configurado' },
      { name: 'status', label: 'Status', type: 'select', defaultValue: 'aberta', options: [
        { value: 'aberta', label: 'Aberta' },
        { value: 'aguardando_aprovacao', label: 'Aguardando aprovação' },
        { value: 'aprovada', label: 'Aprovada' },
        { value: 'em_execucao', label: 'Em execução' },
        { value: 'concluida', label: 'Concluída' },
        { value: 'cancelada', label: 'Cancelada' },
        { value: 'reprovada', label: 'Reprovada' },
      ], tooltip: 'Fluxo da OS: Aberta → Aguardando aprovação → Aprovada → Em execução → Concluída' },
      { name: 'data_inicio', label: 'Data início execução', type: 'date', tooltip: 'Data em que a oficina começou o serviço' },
      { name: 'data_conclusao', label: 'Data de conclusão', type: 'date', tooltip: 'Data em que o veículo foi entregue após o serviço' },
      { name: 'valor_final', label: 'Valor final (R$)', type: 'number', placeholder: '0,00', tooltip: 'Valor real cobrado pela oficina (pode diferir do estimado)' },
      { name: 'motivo_reprovacao', label: 'Motivo da reprovação', type: 'textarea', placeholder: 'Descreva o motivo caso a OS seja reprovada', tooltip: 'Obrigatório ao reprovar uma OS — fica registrado no histórico' },
      { name: 'observacoes', label: 'Observações', type: 'textarea', placeholder: 'Informações adicionais, garantia de peças, próxima revisão, etc.' },
      { name: 'ativo', label: 'Ativo', type: 'checkbox', defaultValue: true },
    ],
  },
  veiculos_documentos: {
    title: 'Documentos de frota',
    subtitle: 'Controle de vencimento dos documentos dos veículos: CRLV, seguro, licenças, tacógrafo e outros.',
    resource: 'veiculos_documentos',
    createScope: 'create.veiculos_documentos',
    filters: [
      { name: 'tipo_documento', label: 'Tipo', type: 'text' },
      { name: 'status', label: 'Status', type: 'text' },
      {
        name: 'veiculo_id',
        label: 'Veículo',
        type: 'select',
        relation: 'veiculos',
        optionLabel: 'placa',
        searchable: true,
      },
    ],
    columns: [
      { key: 'veiculo_id', label: 'Veículo', relation: 'veiculos', optionLabel: 'placa' },
      { key: 'tipo_documento', label: 'Tipo' },
      { key: 'numero_documento', label: 'Número' },
      { key: 'data_emissao', label: 'Emissão', type: 'date' },
      { key: 'data_validade', label: 'Validade', type: 'date' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      {
        name: 'veiculo_id',
        label: 'Veículo',
        type: 'select',
        required: true,
        relation: 'veiculos',
        optionLabel: 'placa',
        searchable: true,
        tooltip: 'Placa do veículo ao qual o documento pertence',
      },
      {
        name: 'tipo_documento',
        label: 'Tipo de documento',
        type: 'select',
        required: true,
        options: [
          { value: 'crlv', label: 'CRLV — Certificado de Registro e Licenciamento' },
          { value: 'seguro', label: 'Seguro obrigatório (DPVAT) / voluntário' },
          { value: 'tacografo', label: 'Tacógrafo — lacre e calibração' },
          { value: 'inspecao_veicular', label: 'Inspeção veicular' },
          { value: 'habilitacao_especial', label: 'Habilitação especial / ANTT' },
          { value: 'alvara_transporte', label: 'Alvará / licença de transporte' },
          { value: 'certificado_produto_perigoso', label: 'Certificado de produto perigoso' },
          { value: 'outro', label: 'Outro' },
        ],
      },
      { name: 'numero_documento', label: 'Número / código', type: 'text', placeholder: 'Número do documento' },
      { name: 'orgao_emissor', label: 'Órgão emissor', type: 'text', placeholder: 'Ex.: DETRAN, ANTT, INMETRO' },
      { name: 'data_emissao', label: 'Data de emissão', type: 'date' },
      { name: 'data_validade', label: 'Data de validade', type: 'date', required: true, tooltip: 'Vencimento do documento — usado para alertas automáticos' },
      { name: 'prazo_renovacao_dias', label: 'Prazo de alerta (dias antes)', type: 'number', defaultValue: 30, placeholder: '30', tooltip: 'Quantos dias antes do vencimento emitir alerta' },
      { name: 'arquivo_url', label: 'URL do arquivo digitalizado', type: 'text', placeholder: 'https://...' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        defaultValue: 'valido',
        options: [
          { value: 'valido', label: 'Válido' },
          { value: 'proximo_vencimento', label: 'Próximo do vencimento' },
          { value: 'vencido', label: 'Vencido' },
          { value: 'em_renovacao', label: 'Em renovação' },
        ],
      },
      { name: 'observacoes', label: 'Observações', type: 'textarea', placeholder: 'Detalhes, restrições, número de processo' },
    ],
  },
  horas_extras: {
    title: 'Horas Extras',
    subtitle: 'Registro, controle e aprovação de horas extras por colaborador e filial.',
    resource: 'horas_extras',
    createScope: 'create.horas_extras',
    filters: [
      { name: 'filial_id', label: 'Filial', type: 'select', relation: 'filiais', optionLabel: 'cidade' },
      {
        name: 'colaborador_id',
        label: 'Colaborador',
        type: 'select',
        relation: 'colaboradores',
        optionLabel: 'nome_completo',
        searchable: true,
        dependsOn: 'filial_id',
        dependsOnRelationField: 'filial_id',
      },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { value: 'pendente', label: 'Pendente' },
          { value: 'aprovado', label: 'Aprovado' },
          { value: 'reprovado', label: 'Reprovado' },
        ],
      },
      { name: 'data_solicitacao', label: 'Data', type: 'date' },
    ],
    columns: [
      { key: 'numero_solicitacao', label: 'N° Solicitação' },
      { key: 'data_solicitacao', label: 'Data', type: 'date' },
      { key: 'colaborador_id', label: 'Colaborador', relation: 'colaboradores', optionLabel: 'nome_completo' },
      { key: 'filial_id', label: 'Filial', relation: 'filiais', optionLabel: 'cidade' },
      { key: 'qtd_horas', label: 'Horas' },
      { key: 'motivo', label: 'Motivo' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'filial_id', label: 'Filial', type: 'select', required: true, relation: 'filiais', optionLabel: 'cidade' },
      {
        name: 'colaborador_id',
        label: 'Colaborador',
        type: 'select',
        required: true,
        relation: 'colaboradores',
        optionLabel: 'nome_completo',
        searchable: true,
        dependsOn: 'filial_id',
        dependsOnRelationField: 'filial_id',
        requireDependsOn: true,
      },
      { name: 'data_solicitacao', label: 'Data da solicitação', type: 'date', required: true },
      { name: 'qtd_horas', label: 'Quantidade de horas', type: 'number', required: true, defaultValue: 1, placeholder: 'Ex.: 2.5', tooltip: 'Horas extras realizadas ou solicitadas. Use decimal para frações (ex.: 1.5 = 1h30)' },
      { name: 'motivo', label: 'Motivo', type: 'textarea', required: true, placeholder: 'Descreva a necessidade operacional que justifica as horas extras' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        defaultValue: 'pendente',
        options: [
          { value: 'pendente', label: 'Pendente — aguardando aprovação' },
          { value: 'aprovado', label: 'Aprovado' },
          { value: 'reprovado', label: 'Reprovado' },
        ],
      },
      { name: 'justificativa_gestor', label: 'Justificativa do gestor', type: 'textarea', placeholder: 'Preenchido pelo aprovador — motivo da aprovação ou reprovação', tooltip: 'Campo para o gestor registrar o motivo da decisão' },
      { name: 'data_aprovacao', label: 'Data da aprovação', type: 'date' },
    ],
  },
}
